### ISSUE TITLE
rmMbUploadLimit undefined

### ISSUE THREAD

**Issue by agurvich** [tkukurin/google-drive-remarkable-sync#7]
`rmMbUploadLimit` is undefined in [Synchronizer.js](https://github.com/tkukurin/google-drive-remarkable-sync/blob/master/Synchronizer.js). 

Easily rectified w/ `const rmMbUploadLimit = 100000000000;` at the top (since I'm not sure what the limit is and what units it should be in, b.c. putting 100 Mb didn't seem to work :\).

**Comment by tkukurin** [comment]
Thanks, fixed!
