### ISSUE TITLE
rDoc and cachedDoc are just strings, without Success, Version, Parent, url, etc... attributes

### ISSUE THREAD

**Issue by agurvich** [tkukurin/google-drive-remarkable-sync#8]
As far as I can tell, the variables `rDoc` and `cachedDoc` are just strings that do not have the necessary attributes to check versions, get download url, etc... in [Synchronizer.js:downloadUpdates](https://github.com/tkukurin/google-drive-remarkable-sync/blob/master/Synchronizer.js#L333). 

As a result, no updates are ever downloaded because `null > null` evaluates to `false` in the version check.

![image](https://user-images.githubusercontent.com/7799423/113324760-1c96ba80-92dd-11eb-9758-5497cf8b2dff.png)

**Comment by tkukurin** [comment]
The first time around, cache file will be empty and hence all downloads skipped.

Code in [Synchronizer:401](https://github.com/tkukurin/google-drive-remarkable-sync/blob/master/Synchronizer.js#L401) should generate an initial document list (`ReMarkable.json`), and all changes made on ReMarkable will be synced from that point on.

Does that make sense? NB, this is a script I've modified for my own personal use-case so its behavior is certainly a bit strange in some places. :)

**Comment by agurvich** [comment]
For sure, I understand. I've tried re-running a couple of times and I've even removed the cache and it's been repopulated a couple of times but nothing has been coming down the pipe. I appreciate your help, and if it turns out to be too much I'm happy to leave you be and fuss with it in peace.

**Comment by agurvich** [comment]
Took another, look, turns out the issue was this line: 

`let rDocList = this.syncMode === "2way-full" ? this.rDocList : rDescIdsList;`
which should be replaced with: 
`let rDocList = this.syncMode === "2way-full" ? this.rDocList : this.rDocList.filter(
          rdoc => rDescIdsList.includes(rdoc.ID));`

At: https://github.com/tkukurin/google-drive-remarkable-sync/blob/master/Synchronizer.js#L401

rDescIdsList is only the strings containing IDs, this has also led to a separate issue where the cache is only being populated with the IDs. This leads to an error in this block when you try and read the `.Parent` attribute of `cachedDoc` which is `undefined` in this block: 

https://github.com/tkukurin/google-drive-remarkable-sync/blob/master/Synchronizer.js#L343

It seems like this should also be a problem for the `!cachedDoc` case (which is where I'm at right now b.c. I deleted the bad cache). 

Not sure how this is working for you, but I'll keep at it, I think I should be able to put in a few conditionals to handle the `!cachedDoc` case and then I can probably put in a pull request or something.

**Comment by agurvich** [comment]
Turns out all it took was: 

`let gdOldParentId = cachedDoc ? this.UUIDToGdId[cachedDoc.Parent]: null;`

at https://github.com/tkukurin/google-drive-remarkable-sync/blob/master/Synchronizer.js#L355

I'll stop spamming you now, thanks for putting this together, really excited to get it fully working w/ the `.bin` conversion and stuff. Cheers!

**Comment by tkukurin** [comment]
No worries, glad to see you got it working!
